# Generated by Django 2.2.2 on 2019-10-09 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('no_of_plots_owned', models.IntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedCrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop1', to='main_app.Crop')),
                ('crop2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop2', to='main_app.Crop')),
                ('crop3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop3', to='main_app.Crop')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.OwnerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RentedPlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_crop1', to='main_app.Crop')),
                ('crop2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_crop2', to='main_app.Crop')),
                ('crop3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_crop3', to='main_app.Crop')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.OwnerProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.OwnerProfile'),
        ),
    ]
